### PR TITLE
SMW 2.1 -> 2.5.8

### PR DESCRIPTION
**Pull request by hcooper**
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/RopeWiki/app/pull/55).
* #105
* #104
* __->__ #55
* #103

### CODE REVIEW

**Comment by BenjaminPelletier** [comment]
Just to give a review update, I am definitely still planning on approving -- the thing I want to do before that is independently verify deployment on my GCP dev instance.  Thanks for this work!

**Comment by hcooper** [comment]
Argh. Just found this breaks SemanticForms (the tab disappears, but the extension is still listed in Special:Version).

Bisecting it, even just upgrading SMW one version, to 2.2.0, breaks it.

**Comment by hcooper** [comment]
After waaaay too much debugging at a low level (upgrading, downgrading, printing, dumping, etc), I went back a re-read the docs.

https://www.mediawiki.org/wiki/Extension:Page_Forms/The_%22edit_with_form%22_tab

A (the?) fix is just to add a line to each Category page (Canyon, Region, etc) defining the default form template. For example:

Here: http://ropewiki2.ak/Category:Regions/edit add the line `{{#default_form:Region}}`

It's not clear what's changed in the upgrade (it's definitely tied to moving to above SMW 2.1), but I like this as a fix.

As an aside, I don't think we need to keep our own copy of the old SemanticForms repo ourselves. Cloning the PageForms repo and checking out branch 3.7 (the last version of SemanticForms) seems to work fine.

**Comment by hcooper** [comment]
I'm testing the default form conversion on some lesser used categories to check they can be switched before the upgrade. e.g. https://ropewiki.com/Category:Knots

**Review by BenjaminPelletier — APPROVED** [review]
Looks like you have good testing for the change (thanks for that work!), so let's update :)

**Pull request merged**
