### PR TITLE
Use juanluisbaptiste Postfix config

### PR DESCRIPTION
**Pull request by casconed**

### CODE REVIEW

**Comment by casconed** [comment]
@BenjaminPelletier checking in on this

**Review by BenjaminPelletier — COMMENTED** [review]
I apologize for not noticing this earlier; please feel free to reach out directly via email, Facebook, or Slack if I'm not responsive in the future.

I confirm that this PR successfully enables sending email from the container it creates when running the `echo` command mentioned [here](https://github.com/RopeWiki/app/issues/6#issuecomment-947284101).  The setup for that is to build the container per README, run the container per README (using SMTP_PORT=465 per [Gmail SMTP instructions](https://serversmtp.com/smtp-gmail-configuration/) and an application-specific password), open a terminal in that container with `docker container exec -it postfix /bin/bash`, and then run `echo "Test message from local Docker container" | mail -s "Local mail test" recipient_email@gmail.com`.

So, this PR does make progress on email by setting up a system that can successfully send email as desired.  However, this example still has to be integrated into the main site to resolve #6.  The previous version of `email_test` used `ubuntu:14.04` as the base image so that the Dockerfile instructions could simply be added to the `webserver` image.  This PR uses an `alpine` base image, so will need to be adapted to be used in the `webserver` image, or else we will need to set up another container in the deployment and then configure the `webserver` container to call this new container.  If the separate-container strategy were adopted, this `email_test` would need to define a second container representing the `webserver` image starting from `ubuntu:14.04` which demonstrates how to configure that client appropriately to use the separate container as an SMTP relay.  If the same-container strategy were adopted, this `email_test` would need to change its Dockerfile to start from `ubuntu:14.04` rather than `alpine`.

If the client container were configured to use a separate SMTP relay container, I'm not sure why we wouldn't just have the client container talk directly to Gmail as the SMTP relay, thus making the separate container unnecessary.  If we want to adopt this approach in a single container, then we need to rewrite the Dockerfile and script to work in Ubuntu 14 rather than Alpine and I think we would take a different approach for simplicity there.  For instance, this additional Dockerfile command adopts a lot of the configuration in `run.sh`:

```
RUN postconf -e "myhostname = dev.ropewiki.com" && \
    postconf -e "mydomain = ropewiki.com" && \
    postconf -e "mydestination = localhost" && \
    postconf -e "myorigin = \$mydomain" && \
    postconf -e "relayhost = [smtp.gmail.com]:465" && \
    postconf -e "smtp_use_tls = yes" && \
    postconf -e "smtp_sasl_auth_enable = yes" && \
    postconf -e "smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd" && \
    postconf -e "smtp_sasl_security_options = noanonymous" && \
    postconf -e "smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt" && \
    postconf -e "always_add_missing_headers = no" && \
    postconf -e "smtp_host_lookup = native,dns" && \
    postconf -e "smtp_tls_wrappermode = yes" && \
    postconf -e "smtp_tls_security_level = encrypt" && \
    echo "[smtp.gmail.com]:465 ${SMTP_USERNAME}:${SMTP_PASSWORD}" >> /etc/postfix/sasl_passwd && \
    postmap /etc/postfix/sasl_passwd && \
    postconf -e "mynetworks = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
```

**Comment by casconed** [comment]
No worries about the delay! 

I don't know that I have a strong opinion about same-container vs separate, although i tend to use one container per service. If you don't feel strongly either way I can define the second container for the web service as you mention above and push up the change to this PR?

**Comment by BenjaminPelletier** [comment]
The [webserver](https://github.com/RopeWiki/app/tree/master/webserver) container needs the capability to send mail, regardless of how that's implemented -- that's what we're trying to solve here ultimately.  It seems like if it's configured to send mail to a separate relay container which is configured to send mail to the Gmail SMTP server, it would probably be simpler just to configure the webserver container to talk directly to the SMTP server without the relay in the middle.  But, any solution that enables the webserver container to send mail (or, equivalently, a demonstration that sends mail starting from the `ubuntu:14.04` image) would be great, even if it involves 2 containers.

**Comment by hcooper** [comment]
Something along these lines is being done in https://github.com/RopeWiki/app/pull/26 - so doing some housekeeping and closing this PR.

**Pull request closed without merging**
