### PR TITLE
Add Google Maps API key

### LINKED ISSUE #47: PHP errors on location search
PHP errors on location search: https://ropewiki.com/Location?jform&locsearchchk=on&locname=seattle&locdist=30mi&skinuser=

```
Notice: Undefined index: egMapsGMaps3ApiKey in /usr/share/nginx/html/ropewiki/vendor/mediawiki/maps/includes/geocoders/Maps_GoogleGeocoder.php on line 41

Notice: Undefined index: egMapsGMaps3ApiKey in /usr/share/nginx/html/ropewiki/vendor/mediawiki/maps/includes/geocoders/Maps_GoogleGeocoder.php on line 42

Notice: Undefined index: egMapsGMaps3ApiVersion in /usr/share/nginx/html/ropewiki/vendor/mediawiki/maps/includes/geocoders/Maps_GoogleGeocoder.php on line 44

Notice: Undefined index: egMapsGMaps3ApiVersion in /usr/share/nginx/html/ropewiki/vendor/mediawiki/maps/includes/geocoders/Maps_GoogleGeocoder.php on line 45
```

### PR DESCRIPTION
**Pull request by llamafilm**
Fixes #47

### CODE REVIEW

**Comment by BenjaminPelletier** [comment]
Is the API key a secret?  If not, could it go in the site config rather than the required environment variables?

**Comment by llamafilm** [comment]
The key is linked to my credit card so I'd prefer to keep it secret.  The risk is low because it can only be used from `*.ropewiki.com` but it might be possible for some hacker to do some DNS spoofing trick.
As long as we stay below 40K requests per month there is no cost.

**Comment by hcooper** [comment]
Thanks for trying to fix this issue.

Existing Google Maps API keys are already set here: https://github.com/RopeWiki/commonjs/blob/master/commonjs/lib/constants.js#L27 . The background to this other repo is that all the javascript (which powers a lot of features) gets merged together, and then copied to the main mediawiki javascript file here: http://ropewiki.ak/index.php?title=MediaWiki:Common.js

All the mapping on the rest of the site uses these keys. And actually [the comments](https://www.facebook.com/groups/ropewiki/posts/3413913938821923/?comment_id=3414442972102353&__cft__[0]=AZWkTIDevGp0TsZR7ERqKkSM74XiZiAoIKqXPPneQathUDF9ctrKr2tqXaSbibKx9axj4sEB92FtWNrRt_GGxdD3gvc_2r_H1UmzPifdWZeySn2VJiYPj4Gj_l6I4K-kYiZvdJ6GxbC4WfDTKCjT-wQz-A6SDFlp_-gl4hkPtMocGfCsO0XyBg7-GnnokSnksAA&__tn__=R]-R) from @catware2 say "/Location" was disabled on purpose years ago.

So I think we've two options:

 1. Modify "/Location" to use the javascript keys like everywhere else on the site.
 2. Just delete "/Location" (The only link I can find to it is on this page: https://ropewiki.com/Beta).

I prefer 2.

As an aside, and something which would be really helpful... I have a proposal for managing these custom constants better. Rather than defining them in the main js file, the js code should attempt to first read them from a file called "/custom_constants.js". This file is not checked into the main repo, and is only used when running dev versions of the site. It then falls back to using the default production codes if this file doesn't exist. We can then delete all the extra keys from the main file, and don't have to do the whole mess of checking in, building js, and copying over to run a new dev site.

**Comment by llamafilm** [comment]
I agree the utility of the search feature is fairly low.  But it seemed like an easy fix, and free if we stay below the $200 monthly credit.  Either way, this was a fun way for me to get familiar with the code 😄 .

If you want to disable it instead, we would also have to change https://ropewiki.com/World which is the **Map** link in the main sidebar.  Try to search for anything on that page and it shows ugly php errors.

**Comment by hcooper** [comment]
My main priority is to avoid duplicating API keys, making the site harder to manage. (The whole commonjs setup isn't particularly nice, but at least it's all in one place!).

> also have to change https://ropewiki.com/World which is the Map link...

Removing the Search option can be done in the Region template, here:

image

I'd suggest just starting with some `<!-- -->` comments! (Welcome to managing code via mediawiki - it, umhh, really sucks!).


>  if it doesn't slow down the site

My theory is that directly fetching a <1K static text file will be an order of magnitude faster than the rest of commonjs. commonjs is a quarter of a megabyte of text fetched from Mysql by PHP, that's then shipped over the internet to your browser, parsed and executed. :-)

I've made a new issue for this proposal (https://github.com/RopeWiki/app/issues/59), so we can keep this discussion related to the maps issue.

**Pull request closed without merging**
